### ISSUE TITLE
Difference of learning rate and batch size in the paper

### ISSUE THREAD

**Issue by cloudygoose** [FudanNLP/Irl_gen#2]
Hi,

I notice in the irl_coco code, learning rate for generator and rewarder are both 0.005 and batch size are 512, this is very different from Table1 in the paper.
Which one is better?

Thanks!

**Comment by Gitsamshi** [comment]
Both settings can lead to the results, hypers in the code could produce in a more stable way, I recommend the hypos in the released code.
